import json
from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

SECTION_FIELDS = [
    ("Property Issue Summary", "property_issue_summary"),
    ("Area-wise Observation", "area_wise_observation"),
    ("Probable Root Cause", "probable_root_cause"),
    ("Severity Assessment", "severity_assessment"),
    ("Recommended Actions", "recommended_actions"),
    ("Additional Notes", "additional_notes"),
    ("Missing or Unclear Information", "missing_or_unclear_information"),
]


def _insert_photo(doc, photo_num, photo_manifest):
    key = str(photo_num)
    entry = photo_manifest.get(key)
    if entry and entry["available"] and entry["path"] and os.path.exists(entry["path"]):
        try:
            doc.add_picture(entry["path"], width=Inches(3.5))
            caption = doc.add_paragraph(f"Photo {photo_num}")
            caption.alignment = WD_ALIGN_PARAGRAPH.CENTER
            caption.runs[0].italic = True
            caption.runs[0].font.size = Pt(9)
        except Exception as e:
            doc.add_paragraph(f"[Photo {photo_num} — could not render: {e}]")
    else:
        p = doc.add_paragraph(f"[Photo {photo_num} — Image Not Available]")
        p.runs[0].italic = True
        p.runs[0].font.color.rgb = RGBColor(0x99, 0x00, 0x00)


def build_document(report_areas, photo_manifest, output_path):
    doc = Document()

    title = doc.add_heading("Detailed Diagnosis Report (DDR)", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph("Generated by AI-Assisted Extraction & Analysis Pipeline")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()
    doc.add_page_break()

    for area in report_areas:
        content = area["generated_content"]

        doc.add_heading(f"Impacted Area {area['area_num']}", level=1)

        ref = doc.add_paragraph()
        ref.add_run("Negative-side finding: ").bold = True
        ref.add_run(area["negative_description"])
        ref2 = doc.add_paragraph()
        ref2.add_run("Positive-side (suspected source): ").bold = True
        ref2.add_run(area["positive_description"])

        doc.add_paragraph()

        for heading, field_key in SECTION_FIELDS:
            doc.add_heading(heading, level=2)
            text = content.get(field_key, "Not Available")
            doc.add_paragraph(text)

        doc.add_heading("Negative-Side Photos", level=2)
        for pnum in area["negative_photos"]:
            _insert_photo(doc, pnum, photo_manifest)

        doc.add_heading("Positive-Side Photos (Suspected Source)", level=2)
        for pnum in area["positive_photos"]:
            _insert_photo(doc, pnum, photo_manifest)

        doc.add_page_break()

    doc.save(output_path)
    return output_path


if __name__ == "__main__":
    with open(OUTPUTS_DIR / "ddr_generated_content.json") as f:
        report_areas = json.load(f)
    with open(OUTPUTS_DIR / "photo_manifest.json") as f:
        photo_manifest = json.load(f)

    output_path = OUTPUTS_DIR / "Final_DDR_Report.docx"
    saved_path = build_document(report_areas, photo_manifest, str(output_path))
    print(f"Saved {saved_path}")